### ISSUE TITLE
image not loading

### ISSUE THREAD

**Issue by zhitongLIU** [linmasahiro/vue3-table-lite#1]
hello,

thank you for the component, 
but it seems like images in rows are not getting loaded
![image](https://user-images.githubusercontent.com/6035593/99153488-13e47580-26a9-11eb-867b-60f8fd1462ab.png)
![image](https://user-images.githubusercontent.com/6035593/99153496-23fc5500-26a9-11eb-9d0f-5c50ac4215a4.png)

all the best,

**Comment by linmasahiro** [comment]
> hello,
> 
> thank you for the component,
> but it seems like images in rows are not getting loaded

Please edit `<img class="card-img-top" :src="' + row.logo_src + '" alt=" + row.name + "/>`
to `<img class="card-img-top" src="' + row.logo_src + '" alt=" + row.name + "/>`
it be work!
