### ISSUE TITLE
Is there a way to filter Published and Not Published?

### ISSUE THREAD

**Issue by macellinoss275** [linmasahiro/vue3-table-lite#104]
So I'm using Vue Table Lite, and have been able to implemented the search function. But now I want to have a filter. One of the column of my table is Publication Type that has either one of these value: null (which is displayed Not Published) or the date of the publication.

For example:

Name | Publication Type
---------------------------
A        | Jan 31, 2024 11:54 am
B        | Not Published

Is there a way I could filter it? I want to have a Select input, the first one is not null value which will display any data with published date, and the second one is null value which will display only data with Not Published tag.

**Comment by linmasahiro** [comment]
Hi, @macellinoss275 

You can added select element to your template
```
<select v-model="condition">
  <option value="1">Has date</option>
  <option value="2">Is NULL</option>
</select>
```

and rewrite your table's row's computed method like below.
```
const condition = ref("1");
const table = reactive({
  columns: [
    // ...
    {
      label: "Name",
      field: "name",
      width: "10%",
      sortable: true,
    },
    // ....
  ],
  rows: computed(() => {
    return data.filter(
      (x) => {
        if (searchTerm.value == "1") {
          // your not null value conditions.
          return x.email != null && x.email != "" && x.email != "null";
        }
        if (searchTerm.value == "2") {
          // your null value conditions.
          return !x.email || x.email == "null";
        }
      }
    );
  }),
  totalRecordCount: computed(() => {
    return table.rows.length;
  }),
  sortable: {
    order: "id",
    sort: "asc",
  },
});
```

**Comment by macellinoss275** [comment]
@linmasahiro Thank you so much! It works!

**Comment by macellinoss275** [comment]
@linmasahiro Hello, sorry for reopening this, but I have another problem. While it does work, but now I can't use my Search input in case user want to search something (like a name for example).

This is my current Vue Table Lite code:

```
    const searchTerm = ref('');
    const filterPublished = ref('');

    rows: computed(() => productsAndSolutions.filter((x) => {
        if (searchTerm) {
            return x.system.toLowerCase().includes(searchTerm.value.toLowerCase());
        }

        if (filterPublished.value === '1') {
            return x.published_at !== null;
        } else if (filterPublished.value === '2') {
            return x.published_at === null;
        } else {
            return x;
        }
    })),
```

And this is my Search input and Select input:

```
<input class="form-control ps-35px" type="text" placeholder="Search..." v-model="searchTerm">

<select class="form-select" id="filter-published" v-model="filterPublished">
    <option selected>Select Publication Type</option>
    <option value="1">Published</option>
    <option value="2">Not Published</option>
</select>
```

Is there a way so that user can filter and search at the same time? For example using the previous table, user can search the name "A" and only "A" will be displayed. But then he can filter based on publication type. If he choose "Published", then the data "A" will still be displayed. But if he choose "Not Published", the table will show no data because there is no data with the name "A" with publication type "Not Published".

**Comment by linmasahiro** [comment]
Hi, @macellinoss275 
It's easy.

```
      rows: computed(() => {
        return data.filter(
          (x) => {
            return x.system.toLowerCase().includes(searchTerm.value.toLowerCase());
          }
        ).filter(
          (x) => {
            if (filterPublished.value === '1') {
              return x.published_at !== null;
            }
            if (filterPublished.value === '2') {
              return x.published_at === null;
            }
          }
        );
```

**Comment by macellinoss275** [comment]
@linmasahiro Thank you so much, I didn't know it was possible to chain the filter function.
