### ISSUE TITLE
How to change the checkbox "All Check" button to Indeterminate Checkbox when not all is selected?

### ISSUE THREAD

**Issue by macellinoss275** [linmasahiro/vue3-table-lite#105]
This isn't a massive problem or anything, but when a user click the "select all" checkbox, the that checkbox will be filled with a check mark. But if I remove one of the checked input, the "select all" checkbox itself still display the check mark. Is there a way to make it become Indeterminate Checkbox instead?

There is also a kinda similar problem where a user check one of the input (without selecting "select all" checkbox), the "select all" checkbox doesn't become Indeterminate Checkbox.

Current problem:
![image](https://github.com/linmasahiro/vue3-table-lite/assets/138418079/7921b0f1-671e-4f0b-8267-0522e074665e)

What I want:
![image](https://github.com/linmasahiro/vue3-table-lite/assets/138418079/42905731-ebee-44db-9518-b64d741db90e)

**Comment by linmasahiro** [comment]
Hi, @macellinoss275 
It's not props to support yet. But here has a simple solution.
```
    const tableLoadingFinish = (elements) => {
      document.getElementsByClassName("vtl-thead-checkbox")[0].indeterminate = false;
      // something...
    };

    const updateCheckedRows = (rowsKey) => {
      if (rowsKey.length == 0) {
        document.getElementsByClassName("vtl-thead-checkbox")[0].indeterminate = false;
      }
      if (rowsKey.length > 0 && !document.getElementsByClassName("vtl-thead-checkbox")[0].checked) {
        document.getElementsByClassName("vtl-thead-checkbox")[0].indeterminate = true;
      }
      // something....
    };
```

**Comment by macellinoss275** [comment]
@linmasahiro I tried your solution but it still has a problem like it's the head checkbox is still indeterminate even after I click every single checkbox. Then I modified your code a bit, where I have another variable that counts the total amount of data and use it to become like this:

```
    const updateCheckedRows = (rowsKey) => {
        if (rowsKey.length === 0) {
            document.getElementsByClassName('vtl-thead-checkbox')[0].indeterminate = false;
        }
        if (rowsKey.length > 0 && rowsKey.length < countAll) {
            document.getElementsByClassName('vtl-thead-checkbox')[0].indeterminate = true;
        }
        if (rowsKey.length === countAll && !document.getElementsByClassName("vtl-thead-checkbox")[0].checked) {
            document.getElementsByClassName('vtl-thead-checkbox')[0].indeterminate = false;
        }
    }
```

But this also isn't enough. Assuming there are 4 data, that means there are 1 head checkbox and 4 individual checkbox. If I click the first individual checkbox, then the head checkbox becomes indeterminate. This consistently happen until I check every single individual checkbox, which then the head checkbox turns to checked. Until this the behavior is correct.

Now this is where it starts getting weird. If I uncheck one of the checked individual checkbox, the head checkbox will becomes indeterminate again, which is correct. But then if I check that unchecked individual checkbox again, the head still stays as indeterminate checkbox and not becomes a checked checkbox like it should be.

After doing console log, it seems like the process of that recheck doesn't count towards rowsKey, which I assume why the head checkbox doesn't become checked again.

Please take a look at this demonstration video:
https://github.com/linmasahiro/vue3-table-lite/assets/138418079/b22951a9-5718-41d5-96c2-963ceaa4dd5f

**Comment by macellinoss275** [comment]
@linmasahiro How do I use it? I have upgraded the package to 1.4.0 but nothing happened. Then I tried to give props like this but it also doesn't work:

```
                        <VueTableLite
                            class="vue-table"
                            :has-checkbox="true"
                            :indeterminate="true" // also tried "table.indeterminate" or "table.isIndeterminate"
                        />
```

**Comment by linmasahiro** [comment]
> @linmasahiro How do I use it?

No, you not need do anything.
If row's checkbox will be checked, header's checkbox auto change to indeterminate state.
example: https://codesandbox.io/p/sandbox/vue3-table-lite-forked-hvs5wr?file=%2Fsrc%2FApp.vue%3A4%2C10

**Comment by macellinoss275** [comment]
@linmasahiro Thank you, it works after I restarted my VSCode and rerun pnpm run dev.
