### ISSUE TITLE
Getting Warning for WATCH_ARRAY from vue3 

### ISSUE THREAD

**Issue by lilz-sofia** [linmasahiro/vue3-table-lite#106]
Hi, thank you very much for creating this library and this seemed like a very easy to integrate library for vue3 applications.
However, I am getting the following warning from vue3 after using this library. This is probably due to not using the `deep` option in the watch functions:

````
[Vue warn]: (deprecation WATCH_ARRAY) "watch" option or vm.$watch on an array value will no longer 
trigger on array mutation unless the "deep" option is specified. 
If current usage is intended, you can disable the compat behavior and suppress this warning with:

  configureCompat({ WATCH_ARRAY: false })

 Details: https://v3-migration.vuejs.org/breaking-changes/watch.html 
 at <MyTable is-static-mode=true is-slot-mode=true columns= (3) [{…}, {…}, {…}] 
 ... > 
````

I guess this is not an intended usage, would be glad if this could be fixed with new release.

**Comment by linmasahiro** [comment]
Hi, @lilz-sofia 
I am always use Vue.js 3.x and I don't know how to implement this issue.
More details or implement it on Codepen, thx.

**Comment by lilz-sofia** [comment]
Hi, @linmasahiro 
Thank you for your quick response. Maybe since I am using the vue3 migration build (`@vue/compat`) I am getting this warning. It usually doesn't show such warnings on vue3. You can find the details on the warning here:
https://v3-migration.vuejs.org/breaking-changes/watch.html 

I looked into the watch function in `my-table` component of your library and found that the watch function that is used for `props.row` is watching an array. So it is recommended by vue3 to use `deep:true` option or else it will not trigger re-rendering on mutation of the array.

Let me know if you need more details..

**Comment by linmasahiro** [comment]
Hi, @lilz-sofia 
I added deep option to v1.4.0 and released, upgrade to 1.4.0 and check it please.

**Comment by lilz-sofia** [comment]
Thank you. I'll check and let you know

**Comment by lilz-sofia** [comment]
Hi @linmasahiro,
I check and confirm that the warning has been resolved. Thank you for for the quick update! 🚀
