### ISSUE TITLE
get-now-page event: How to use it

### ISSUE THREAD

**Issue by tpzar** [linmasahiro/vue3-table-lite#109]
Hello, I have a backend which returns already paginated data like /get_items?page=0&limit=50
I would like to show data on table so that if I click on pagination button [2] frontend make an axios call to API server like /get_items?page=1&limit=50
I guess the get-now-page function could be useful in this case but I'm not able to find any example where event called get-now-page is used.

Could you show me an example on how to pass pageNo variable to doSearch function, please?

**Comment by linmasahiro** [comment]
Hi, @tpzar 
`get-now-page` is always calling after page changed and it's let you can pass to other feature not of the table, not designed for search.
So you should not pass to `doSearch`, you should be calculate pageNo by `offset` and `limit` like below

```
  const doSearch = (offset, limit, order, sort) => {
      table.isLoading = true;
      let pageNo = 0;
      if (offset !== undefined) {
        // changed page from table
        pageNo = offset / limit;
      }

      (async () => {
        let rows = [];
        let totalRecordCount = 0;
        try {
          await axios.get("/get_items?page=" + pageNo + "&limit=" + limit).then(function(response) {
            if (response.data.status == "OK") {
              rows = response.data.records;
              totalRecordCount = parseInt(response.data.totalRecordCount);
              table.sortable.order = searchConditions.order;
              table.sortable.sort = searchConditions.sort;
            }
          });
        } catch (err) {
          console.error("Request Error");
        } finally {
          table.isReSearch = (offset == undefined) ? true : false;
          table.rows = rows;
          table.totalRecordCount = totalRecordCount;
        }
      })();
    }

    // Not need any params on first search.
    doSearch();
```

**Comment by linmasahiro** [comment]
> any changes in `<input v-model="searchTerm">` sends a new request to API server? Based on the provided filter examples I can't figure out how to do it

Filter feature is better for `static-mode`, your table always calling API to get data, so I think you not should be use filter feature, you can use `watch` to listen the search text, maybe like below

```
<template>
  <input v-model="searchTerm">
  <table-lite
    :rows="table.rows"
    ....
  ></table-lite>
</template>

<script>
  // ...
  const searchTerm = ref('');
  watch(
      () => searchTerm,
      () => {
        // if input's text any changed call the API
        doSearch();
      }
    );

    const doSearch = (offset, limit, order, sort) => {
      table.isLoading = true;
      let pageNo = 0;
      if (offset !== undefined) {
        // changed page from table
        pageNo = offset / limit;
      }

      (async () => {
        let rows = [];
        let totalRecordCount = 0;
        try {
          await axios.get("/get_items", {
            params: {
              keyword: searchTerm.value,   // here is your search text
              page: pageNo,
              limit: limit
            }
          }).then(function(response) {
            // here is my response format, follow your api response format
            if (response.data.status == "OK") {
              rows = response.data.records;
              totalRecordCount = parseInt(response.data.totalRecordCount);
              table.sortable.order = searchConditions.order;
              table.sortable.sort = searchConditions.sort;
            }
          });
        } catch (err) {
          console.error("Request Error");
        } finally {
          table.isReSearch = (offset == undefined) ? true : false;
          table.rows = rows;
          table.totalRecordCount = totalRecordCount;
        }
      })();
    }    
</script>
```

**Comment by tpzar** [comment]
Hi, @linmasahiro, the proposed solution using watch strangely is not working to me. The request does not start automatically when I copy a search string in the input field but, if I add a button `<button @click="doSearch()">Search</button>`, a request to `doSearch` is sent. 
Maybe am I missing some parameters or using the wrong table settings?

Following my settings and source code


`<template>
  <div>
    <div style="text-align: left">
      <label>SearchBy:</label><input v-model="searchTerm" />
    </div>
    <table-lite
      :is-slot-mode="true"
      :is-loading="table.isLoading"
      :is-re-search="table.isReSearch"
      :page-size="table.limit"
      :columns="table.columns"
      :rows="table.rows"
      :total="table.totalRecordCount"
      :pageOptions="[ { value: 10, text: 10 }, { value: 25, text: 25 }, { value: 50, text: 50 }, { value: 100, text: 100 } ]"
      :sortable="table.sortable"
      @do-search="doSearch"
      @is-finished="table.isLoading = false"
    >
    </table-lite>
  </div>
</template>

<script>
import { defineComponent, reactive, ref, computed, watch } from "vue";
import TableLite from "vue3-table-lite";
import axios from 'axios';

export default defineComponent({
  name: "App",
  components: { TableLite, },
  setup() {
    const searchTerm = ref(""); // Search text
    watch(
      () => searchTerm,
      () => {
        doSearch();
      }
    );

    // Table config
    const table = reactive({
      isLoading: false,
      isReSearch: false,
      columns: [
      // ...
      ],
      rows: [],
      totalRecordCount: 0,
      limit: 25,
      sortable: {
        order: "id",
        sort: "asc",
      },
    });

    /**
     * Search Event
     */
    const doSearch = (offset, limit, order, sort ) => {
      table.isLoading = true;
      console.log(searchTerm.value)
      limit = table.limit;
      let pageNo = 0;
      if (offset && (offset / limit) >= 1) {
        pageNo = (offset / limit) ;
      }

      // Start get data from Server
      (async () => {
        let rows = [];
        let totalRecordCount = 0;
        try {
          await axios.get("/get_items", {
            params: {
                page: pageNo,
                limit: limit,
                search: searchTerm.value
              }
          }).then(function(response) {
            if (response.status == 200) { 
            rows = response.data.results;
            totalRecordCount = parseInt(response.data.totalCount);
            table.limit = response.data.content.limit;
            table.sortable.order = order;
            table.sortable.sort = sort;
            }
          });    
        } catch (err) {
          console.error("Request Error");  
        } finally {
          table.isResearch = (offset == undefined) ? true : false;
          table.rows = rows;
          table.totalRecordCount = totalRecordCount;
        }
      })();
    /**
     * Table search finished event
     */
    const tableLoadingFinish = (elements) => {
      table.isLoading = false;
    };

    // First get data
    doSearch(0, 25, "id", "asc");

    return {
      table,
      doSearch,
      tableLoadingFinish,
      searchTerm
    };
  },
});
`

**Comment by linmasahiro** [comment]
@tpzar 
Sorry, I forgot used `ref` in the example.
If you wanna watch `ref`, change `() => searchTerm` to `searchTerm`.
```
watch(searchTerm, () => {
  doSearch();
})
```

ref: https://cn.vuejs.org/api/reactivity-core#watch

**Comment by tpzar** [comment]
Thank you so much
