### ISSUE TITLE
Expanding rowClicked for columnClicked and cellClicked

### ISSUE THREAD

**Issue by Boardtale** [linmasahiro/vue3-table-lite#110]
I'm trying to figure out now what cell user clicked. I need to popup some more specific data for specific cell once user click it.
It's missing unfortunatly in this library.

**Comment by linmasahiro** [comment]
> I'm trying to figure out now what cell user clicked. I need to popup some more specific data for specific cell once user click it. It's missing unfortunatly in this library.

Reference the example please
https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/RowClicked.vue

**Comment by Boardtale** [comment]
@linmasahiro Thanks for fast response.
not sure, but I often don't see obvious. There's only row clicked. There's also button slot, yes.
But I don't see how - on row clicked - can I get - what column was clicked along it

**Comment by Boardtale** [comment]
Oh, have you suggested using 'tableLoadingFinish' to add it manually to each cell?

**Comment by linmasahiro** [comment]
If your mean's click any cell and show the cell's data, you can use `V-slot mode` to implement it, I am wrote a simple example, hope helpful you.
[Link](https://codesandbox.io/p/sandbox/vue3-table-lite-forked-tg4ky2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls9upd1j00073b6by8xh7sqe%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls9upd1j00033b6bqkpd29xq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls9upd1j00043b6bg1m7ov8b%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls9upd1j00063b6bvy6u9lcz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls9upd1j00033b6bqkpd29xq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls9upd1j00023b6bp2svvdi8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls9upd1j00033b6bqkpd29xq%2522%252C%2522activeTabId%2522%253A%2522cls9upd1j00023b6bp2svvdi8%2522%257D%252C%2522cls9upd1j00063b6bvy6u9lcz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls9upd1j00053b6boihr9xoq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls9upd1j00063b6bvy6u9lcz%2522%252C%2522activeTabId%2522%253A%2522cls9upd1j00053b6boihr9xoq%2522%257D%252C%2522cls9upd1j00043b6bg1m7ov8b%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls9upd1j00043b6bg1m7ov8b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Boardtale** [comment]
Yeah, thanks! With slots, will work. 
btw I was trying to checkout primevue dataset.. I have to be honest. I have table with like 100x100 rows and it can change dynamically. Your table has no problem at all, insta changes

While dataset from primevue locks my browser for 1 second and browser stops responding for that time 

glad I found your implementation :)
