### ISSUE TITLE
Avoid double click

### ISSUE THREAD

**Issue by tpzar** [linmasahiro/vue3-table-lite#113]
Dear @linmasahiro,
how to avoid double click in `rowClicked` event, equivalently to `@click.once` ? In my case, click starts an await function and it seems I cannot use `settimeout`.

**Comment by linmasahiro** [comment]
> Dear @linmasahiro, how to avoid double click in `rowClicked` event, equivalently to `@click.once` ? In my case, click starts an await function and it seems I cannot use `settimeout`.

Hi , @tpzar 
If you wan't replace vue3-table-lite's source code, have a simple solution on here.

```
    const tmp = ref(null);
    const timer = ref(null);

    /**
     * Row clicked event
     */
    const rowClicked = (row) => {
      if (! tmp.value || tmp.value != row) {
        tmp.value = row;
        clearTimeout(timer.value);
        timer.value = setTimeout(() => {
          tmp.value = null;
        }, 500)
        return;
      }
      if (tmp.value == row) {
          console.log("double clicked!");
          clearTimeout(timer.value);
          tmp.value = null;
        }
    };
```
