### ISSUE TITLE
Failed to resolve component: vue-table-lite 

### ISSUE THREAD

**Issue by mambari** [linmasahiro/vue3-table-lite#17]
Hi, 
First, thank you for your work.
I have some issues to integrate your code. I am beginner level btw.
`[Vue warn]: Failed to resolve component: vue-table-lite`

I am using Vue3 with Ts and I followed the documentation.

Here is my code:

    <template>
      <vue-table-lite
        :is-static-mode='false'
        :has-checkbox='true'
        :is-loading='table.isLoading'
        :is-re-search='table.isReSearch'
        :columns='table.columns'
        :rows='table.rows'
        :total='table.totalRecordCount'
        :sortable='table.sortable'
        :messages='table.messages'
        @do-search="doSearch"
        @is-finished='tableLoadingFinish'
        @return-checked-row='updateCheckedRows'
      />
    </template>
    
    <script lang="ts">
    import { reactive } from 'vue';
    import VueTableLite from 'vue3-table-lite';
    
    export default {
      name: 'AccountsTab',
      setup() : unknown {
        const table = reactive({
          isLoading: false,
          isReSearch: false,
          columns: [
            {
              label: 'ID',
              field: 'id',
              width: '3%',
              sortable: true,
              isKey: true,
            },
            {
              label: 'Name',
              field: 'name',
              width: '10%',
              sortable: true,
              display: function display(row) {
                return (
                  `<a href="#" data-id="${row.user_id}" class="name-btn">${row.name}</button>`
                );
              },
            },
            {
              label: 'Email',
              field: 'email',
              width: '15%',
              sortable: true,
            },
            {
              label: '',
              field: 'quick',
              width: '10%',
              display: function display(row) {
                return (
                  `<button type="button" data-id="${row.user_id}" class="quick-btn">Button</button>`
                );
              },
            },
          ],
          rows: [
            {
              id: 1,
              name: 'TEST1'
            },
            {
              id: 2,
              name: 'TEST2'
            }
          ],
          totalRecordCount: 2,
          sortable: {
            order: 'id',
            sort: 'asc',
          },
          messages: {
            pagingInfo: 'Showing {0}-{1} of {2}',
            pageSizeChangeLabel: 'Row count:',
            gotoPageLabel: 'Go to page:',
            noDataAvailable: 'No data',
          },
        });
 
        const doSearch = (offset, limit, order, sort) => {
          table.isLoading = true;
          table.isReSearch = offset === undefined;
          // do your search event to get newRows and new Total
          table.rows = newRows;
          table.totalRecordCount = newTotal;
          table.sortable.order = order;
          table.sortable.sort = sort;
        };

        const tableLoadingFinish = (elements) => {
          table.isLoading = false;
          Array.prototype.forEach.call(elements, function load(element) {
            if (element.classList.contains('name-btn')) {
              element.addEventListener('click', function click() {
                // do your click event
                console.log(`${this.dataset.id} name-btn click!!`);
              });
            }
            if (element.classList.contains('quick-btn')) {
              // do your click event
              element.addEventListener('click', function click() {
                console.log(`${this.dataset.id} quick-btn click!!`);
              });
            }
          });
        };
    
        const updateCheckedRows = (rowsKey) => {
          // do your checkbox click event
          console.log(rowsKey);
        };
        return (
          {
            accountsList,
            table,
            doSearch,
            tableLoadingFinish,
            updateCheckedRows,
          });
      }
    };
    </script>

    <style>    
    </style>

Best regards,

**Comment by linmasahiro** [comment]
> `[Vue warn]: Failed to resolve component: vue-table-lite`

Hi,
You are forgot add component to your components properties.
```
export default {
  name: 'AccountsTab',
  components: { VueTableLite },
  setup() {
  ...
  }
}
```

**Comment by linmasahiro** [comment]
#4
