### ISSUE TITLE
@is-finished looks like not triggering.

### ISSUE THREAD

**Issue by mambari** [linmasahiro/vue3-table-lite#18]
Hi,
I try to integrate your code. It's really a good job.
But I am facing some issues.
it's loading infinitely. tableLoadingFinish  is not emitting?

here is my code

    <template>
      <vue-table-lite
        :is-static-mode='false'
        :has-checkbox='true'
        :is-loading='table.isLoading'
        :is-re-search='table.isReSearch'
        :columns='table.columns'
        :rows='table.rows'
        :total='table.totalRecordCount'
        :sortable='table.sortable'
        :messages='table.messages'
        @do-search="doSearch"
        @is-finished='tableLoadingFinish'
        @return-checked-row='updateCheckedRows'
      />
    </template>
    
    <script lang="ts">
    import { reactive } from 'vue';
    import VueTableLite from 'vue3-table-lite';
    
    export default {
      name: 'AccountsTab',
      components: {
        VueTableLite,
      },
      setup() : unknown {
        const sampleData1 = function (offst, limit) {
          let sampleoffst = offst;
          sampleoffst += 1;
          type Data = {
            id: number
            name: string
            email: string
          }
          const data: Data[] = [];
          for (let i = sampleoffst; i <= limit; i += 1) {
            data.push({
              id: i,
              name: `TEST${i}`,
              email: `test${i}@example.com`,
            });
          }
          return data;
        };

        const table = reactive({
          isLoading: false,
          isReSearch: false,
          columns: [
            {
              label: 'ID',
              field: 'id',
              width: '3%',
              sortable: true,
              isKey: true,
            },
            {
              label: 'Name',
              field: 'name',
              width: '10%',
              sortable: true,
              display: function display(row) {
                return (
                  `<a href="#" data-id="${row.id}" class="name-btn">${row.name}</button>`
                );
              },
            },
            {
              label: 'Email',
              field: 'email',
              width: '15%',
              sortable: true,
            },
            {
              label: '',
              field: 'quick',
              width: '10%',
              display: function display(row) {
                return (
                  `<button type="button" data-id="${row.id}" class="quick-btn">Button</button>`
                );
              },
            },
          ],
          rows: sampleData1(0, 20),
          totalRecordCount: 20,
          sortable: {
            order: 'id',
            sort: 'asc',
          },
          messages: {
            pagingInfo: 'Showing {0}-{1} of {2}',
            pageSizeChangeLabel: 'Row count:',
            gotoPageLabel: 'Go to page:',
            noDataAvailable: 'No data',
          },
        });
    
        const doSearch = (offset, limit, order, sort) => {
          table.isLoading = true;
          table.isReSearch = offset === undefined;
          // do your search event to get newRows and new Total
          table.rows = sampleData1(0, 10); // newRows
          table.totalRecordCount = 10; // newTotal
          table.sortable.order = order;
          table.sortable.sort = sort;
        };
    
        const tableLoadingFinish = function loadingFinish(elements) {
          table.isLoading = false;
          Array.prototype.forEach.call(elements, function load(element) {
            if (element.classList.contains('name-btn')) {
              element.addEventListener('click', function click(this:any) {
                // do your click event
                console.log(`${this.dataset.id} name-btn click!!`);
              });
            }
            if (element.classList.contains('quick-btn')) {
              // do your click event
              element.addEventListener('click', function click(this:any) {
                console.log(`${this.dataset.id} quick-btn click!!`);
              });
            }
          });
        };
    
        const updateCheckedRows = (rowsKey) => {
          // do your checkbox click event
          console.log(rowsKey);
        };
    
        // your first loading
        doSearch(0, 10, 'id', 'asc');
    
        return (
          {
            table,
            doSearch,
            tableLoadingFinish,
            updateCheckedRows,
          });
      }
    };
    </script>

Best regards,

**Comment by linmasahiro** [comment]
Hi, @mambari 
I rewrite my document. Hope helpful for you.
https://linmasahiro.github.io/vue3-table-lite/dist/
