### ISSUE TITLE
Return rows from API

### ISSUE THREAD

**Issue by AldsTan** [linmasahiro/vue3-table-lite#19]
Hi, thank you for sharing your work. 
I'm new to Vue and I'm having trouble in returning data from my API. I'm using django for the backend.
It would be very helpful to have a more detailed documentation on how to use this, and more examples.

**Comment by linmasahiro** [comment]
Hi @AldsTan 
I rewrite my document. Hope helpful for you.
https://linmasahiro.github.io/vue3-table-lite/dist/
