### ISSUE TITLE
Tutorial as video

### ISSUE THREAD

**Issue by muh-hizbe** [linmasahiro/vue3-table-lite#2]
Hi linmasahiro, maybe you can create a video that helpful everyone for use vue3-table-lite.

**Comment by yardenroee** [comment]
@linmasahiro also, will you please show us how to work with the pagination? the table is not paginating data for me. please help!

**Comment by linmasahiro** [comment]
> @linmasahiro also, will you please show us how to work with the pagination? the table is not paginating data for me. please help!

hi, this component not support filter.
So you need put any finished data to rows property like 
`[
      {
        id: 1,
        name: "TEST1"
      },
      {
        id: 2,
        name: "TEST2"
      },
      {
        id: 3,
        name: "TEST2"
      }
  ]`

example:

```
// your page1 rows
table.rows = [
      {
        id: 1,
        name: "TEST1"
      },
      {
        id: 2,
        name: "TEST3"
      }
......
 ];
```

and you executed something filter method or get server's data after

```
// your page2 rows
table.rows = [
      {
        id: 11,
        name: "TEST11"
      },
     {
        id: 12,
        name: "TEST12"
      }
....
 ];
```
