### ISSUE TITLE
is-slot-mode 

### ISSUE THREAD

**Issue by Zersty** [linmasahiro/vue3-table-lite#21]
I'm looking to only use one of columns with a v-slot to use a component,
But it seems that when you turn is-slot-mode to true that you have to make every column a v-slot

Is there a way I could add a v-slot without having to do them all?

I know display: exists but that doesn't fit my use case as I need to use vue components.

An optional slot mode would be ideal i.e default to not using a slot unless specified <3

**Comment by linmasahiro** [comment]
Hi @Zersty 

> An optional slot mode would be ideal i.e default to not using a slot unless specified <3
Yes, this is a good idea. Thank you.
I am already changed v-slot to optional on version 1.0.9. Hope helpful you.

example: https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/VSlotMode.vue

**Comment by Zersty** [comment]
Thanks very much you rock!!!
