### ISSUE TITLE
add events 

### ISSUE THREAD

**Issue by mouhsineelachbi** [linmasahiro/vue3-table-lite#24]
I'm working with my team using this package but we didn't find event handling yet (v-on or @)

**Comment by linmasahiro** [comment]
> I'm working with my team using this package but we didn't find event handling yet (v-on or @)

Hi @mouhsineelachbi 

Here has event description, maybe can helpful you.
https://linmasahiro.github.io/vue3-table-lite/dist/api.html#events

And we has example on here.
https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/CustomizeStyle.vue

Btw, If you means add new event handling to the component, it is not support now.
