### ISSUE TITLE
Better Semnatics for easier Styling

### ISSUE THREAD

**Issue by PascalAOMS** [linmasahiro/vue3-table-lite#25]
I love the simplicity of this table component.

I'd just wish for better HTML semantics for easier styling.

Take the pagination for instance.
Every item has the same classes and I can't easily distinguish them from being a previous/next page or a number button.
I also don't know which item symbolizes the currently selected page. A `selected` class would be helpful.

**Comment by linmasahiro** [comment]
Hi, @PascalAOMS 
Thank you for request.
I'am already add classes to elements, you can check class name where start with `vtl-` 
https://github.com/linmasahiro/vue3-table-lite/blob/master/src/components/TableLite.vue

And, you can use `::v-deep` to styling elements. Watch the example.
https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/CustomizeStyle.vue

**Comment by linmasahiro** [comment]
#9
