### ISSUE TITLE
How to set row count ? 

### ISSUE THREAD

**Issue by hgalytoby** [linmasahiro/vue3-table-lite#26]
I am learning Vue.

Sorry, my English is not good.

I have looked at https://github.com/linmasahiro/vue3-table-lite/blob/master/src/components/TableLite.vue .

I found row count  v-model=pageSize .

```js
const table = reactive({
    ...
    pageSize: 25
})
```

Row count still 10.

What were my errors?

**Comment by linmasahiro** [comment]
Hi, @hgalytoby 
Please add `page-size` attribute to your component. 
Here has example.

```
<template>
  <table-lite
    ...
    :page-size="table.pageSize"
    ...
  ></table-lite>
</template>
```

**Comment by hgalytoby** [comment]
> :page-size="table.pageSize"

Thank you.
