### ISSUE TITLE
Share the tableLoadingFinish function between several tables.

### ISSUE THREAD

**Issue by grafxflow** [linmasahiro/vue3-table-lite#3]
If I had 2 or more tables components on the same page. Is there anyway I could use the same 'tableLoadingFinish' function between them all but reference the individual table that called it. Currently I am having to duplicate the function 'tableLoadingFinish', 'tableLoadingFinish2' etc. Same for 'table.isLoading = false;' , 'table2.isLoading = false;'

```
const tableLoadingFinish = (elements) => {
  table.isLoading = false;
  Array.prototype.forEach.call(elements, function (element) {
    if (element.classList.contains("name-btn")) {
      element.addEventListener("click", function () {
        // do your click event
        console.log(this.dataset.id + " name-btn click!!");
      });
    }
    if (element.classList.contains("quick-btn")) {
      // do your click event
      element.addEventListener("click", function () {
        console.log(this.dataset.id + " quick-btn click!!");
      });
    }
  });
};
```

**Comment by linmasahiro** [comment]
> If I had 2 or more tables components on the same page. Is there anyway I could use the same 'tableLoadingFinish' function between them all but reference the individual table that called it. Currently I am having to duplicate the function 'tableLoadingFinish', 'tableLoadingFinish2' etc. Same for 'table.isLoading = false;' , 'table2.isLoading = false;'
> 
> ```
> const tableLoadingFinish = (elements) => {
>   table.isLoading = false;
>   Array.prototype.forEach.call(elements, function (element) {
>     if (element.classList.contains("name-btn")) {
>       element.addEventListener("click", function () {
>         // do your click event
>         console.log(this.dataset.id + " name-btn click!!");
>       });
>     }
>     if (element.classList.contains("quick-btn")) {
>       // do your click event
>       element.addEventListener("click", function () {
>         console.log(this.dataset.id + " quick-btn click!!");
>       });
>     }
>   });
> };
> ```

Hi, if you have 2 or more tables on the same page and hope to use same finish event. You can write code like 

HTML:
 ```
 <table-lite
    ...
    @is-finished="tableLoadingFinish($event, table)"
  ></table-lite>
  <table-lite
    ...
    @is-finished="tableLoadingFinish($event, table2)"
  ></table-lite>
```

JavaScript:
```
const tableLoadingFinish = (elements, localTable) => {
    localTable.isLoading = false;
    Array.prototype.forEach.call(elements, function (element) {
      if (element.classList.contains("name-btn")) {
        element.addEventListener("click", function () {
        console.log(this.dataset.id + " name-btn click!!");
        });
      }
      if (element.classList.contains("quick-btn")) {
        element.addEventListener("click", function () {
          console.log(this.dataset.id + " quick-btn click!!");
        });
      }
    });
  };
```

**Comment by grafxflow** [comment]
@linmasahiro  That's great :) Can the same be done for the doSearch?

**Comment by linmasahiro** [comment]
> @linmasahiro That's great :) Can the same be done for the doSearch?

@grafxflow Yes, but has something difference to write event callback.

HTML:

  ```
<table-lite
    ...
    @do-search="(...args) => doSearch(args[0], args[1], args[2], args[3], table)"
    ....
  ></table-lite>
<table-lite
    ...
    @do-search="(...args) => doSearch(args[0], args[1], args[2], args[3], table2)"
    ....
></table-lite>
```

JavaScript:
 ```
   const doSearch = (offset, limit, order, sort, localTable) => {
      localTable.isLoading = true;
      setTimeout(() => {
        localTable.isReSearch = offset == undefined ? true : false;
        if (offset >= 10 || limit >= 20) {
          limit = 20;
        }
        if (sort == "asc") {
          localTable.rows = sampleData1(offset, limit);
        } else {
          localTable.rows = sampleData2(offset, limit);
        }
        localTable.totalRecordCount = 20;
        localTable.sortable.order = order;
        localTable.sortable.sort = sort;
      }, 600);
    };
```
