### ISSUE TITLE
V-Slot mode with search filter

### ISSUE THREAD

**Issue by prajit21** [linmasahiro/vue3-table-lite#30]
Is there is any example for V-Slot mode with search filter ?

**Comment by prajit21** [comment]
can you please add filter with v-slot mode ?

**Comment by linmasahiro** [comment]
> Is there is any example for V-Slot mode with search filter ?

Hi @prajit21 

I am uploaded example on here. Check it.
https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/FilterWithVSlotMode.vue

**Comment by prajit21** [comment]
Thanks you so much for that :)

**Comment by prajit21** [comment]
I have used same example but pagination, sorting not working any solution ?

**Comment by linmasahiro** [comment]
> I have used same example but pagination, sorting not working any solution ?

Hi, @prajit21 
I am try to run my example again, and I sure it's work.
Maybe you can fork my repository and follow under step to run and check it.

```
1. Edit advance.ts and save.
  - import Filter from './examples/Filter.vue'
  + import Filter from './examples/FilterWithVSlotMode.vue'

2. $ npm run serve
3. Access `http://localhost:8080/advanced.html#filter`
```

**Comment by prajit21** [comment]
Hello @linmasahiro 
Actually I have implemented get product api and now we are using doSearch method so pagination is working perfectly but i am not able to implement search functionality. 
so is there any way to use search and doSearch Method simultaneity ?

**Comment by linmasahiro** [comment]
> Hello @linmasahiro
> so is there any way to use search and doSearch Method simultaneity ?

Hi @prajit21 
You can refs https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/Filter2.vue 
and rewrite myRequest to implement get your api data like doSearch().

**Comment by linmasahiro** [comment]
I am closing this issue. If you still have problem, reopen the issue.
