### ISSUE TITLE
Positionable headers

### ISSUE THREAD

**Issue by RaskaTheFurry** [linmasahiro/vue3-table-lite#32]
Hello,

It would be great if you could position headers of each column ( left ( default ), center, right ). We put numbers to the right and I dont see any option to do it for headers or to stylize headers individually.

Also, this table is really nice and easy to use, really great work.

**Comment by linmasahiro** [comment]
Hi, @RaskaTheFurry 
If you want to change style, you can ref [here](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/CustomizeStyle.vue)
You will be not change any code and implement it.

Right position headers of 2nd column:
```
::v-deep(.vtl-table .vtl-thead .vtl-thead-th:nth-child(2)) {
  text-align: right;
}
```

**Comment by RaskaTheFurry** [comment]
Hello,
sorry for late answer

it would be great if we could use something like "Class and Style Bindings" even for headers instead of just using <style>. This would allow us to style even headers using conditions. A thing that is only possible with slots right now and only to data, if I undestand this component correctly.

**Comment by teguhsatria892** [comment]
better you give more props to set the position, like center, left or right, not only for header, but for column too,

**Comment by linmasahiro** [comment]
> better you give more props to set the position, like center, left or right, not only for header, but for column too,

You can use 「columnClasses」or 「columnStyles」 to set the position or other.

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
