### ISSUE TITLE
Suggest removal of .card wrappers

### ISSUE THREAD

**Issue by titusdecali** [linmasahiro/vue3-table-lite#33]
The `div.card`, `div.cart-body`, `.div.card-title` wrappers are causing problems with alignment in my app. I suggest removing them for a few reasons:

- They are unneccesary and can cause styling conflicts
- Naming a div `.card` is too generic which may easily conflict with other styles since there is not a parent wrapper (and adding one is also unneccesary)
- Although `title` can be passed via props, this isn't even documented in the documentation and also doesn't add any value to this library

**Comment by linmasahiro** [comment]
Hi, @titusdecali , thanks your advice!
Many unnecessary class was forget removed it after test.
So, I am adjust class-name to avoid conflict, I hope it will be solve this troubles.

**Comment by linmasahiro** [comment]
> Hello, I expected this! Many thanks!
> 
> What about margin-left/right: -15px on vtl-row? This expands the table on the sides.

Hi, @alexey-us , thanks for your kindly reminder!! It's Bug and I always used Bootstrap so I Didn't noticed.
I am already removed it on v1.1.8-2.

**Comment by alexey-us** [comment]
Many thanks!

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
