### ISSUE TITLE
unable to add a click event in the display function

### ISSUE THREAD

**Issue by sumifru-codebase** [linmasahiro/vue3-table-lite#34]
Is it possible to have an 'onclick' event on the display function? I've been trying to do it, to no results.

**Comment by linmasahiro** [comment]
Hi, @sumifru-codebase 

> Is it possible to have an 'onclick' event on the display function? I've been trying to do it, to no results.

Yes, you can ref this [issue](https://github.com/linmasahiro/vue3-table-lite/issues/10#issuecomment-911147455)

** Your HTML element will be need `is-rows-el` class's name in display function. **

**Comment by sumifru-codebase** [comment]
Thanks! Worked like a charm 😄 

In case someone other than me struggled with this, here is my code:

columns (display):
`display: function (row) {
            return `<button class="button is-rows-el view-data" data-id="${row.id}"><span class="material-icons">view_list</span></button>`;
          },`

is-finished:
`const loadedData = (elements) => {
      // table.isLoading = false;
      Array.prototype.forEach.call(elements, function (element) {
        let id = element.getAttribute("data-id");
        if (element.classList.contains("view-data")) {
          element.addEventListener("click", () => viewData(id));
        }
      });
    };`
