### ISSUE TITLE
suggest to bind row data with the return-checked-rows event

### ISSUE THREAD

**Issue by sumifru-codebase** [linmasahiro/vue3-table-lite#35]
Currently, the return value of the said event is a just a string.

I highly suggest that the return value should be the row data itself in order to do more customization on the component.

**Comment by linmasahiro** [comment]
Hi, @sumifru-codebase , I am already added feature what you want.
Please check [document](https://linmasahiro.github.io/vue3-table-lite/dist/api.html#props) and search `checked-return-type`

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
