### ISSUE TITLE
Suggest to add dynamic row classes

### ISSUE THREAD

**Issue by alexey-us** [linmasahiro/vue3-table-lite#36]
Please add the possibility of dynamic classes for the row.

For example, I want to change background color depending of row property.

in TableLite.vue add prop 'rowClasses'
~~~javascript
    rowClasses: {
      type: Function,
      default: () => []
    },
~~~

and add :class="rowClasses(row) to 'tr' rendering template.

Now in component using I can write function:
~~~javascript
      rowClasses(row) {
          let classes = [];
          if (row.category.indexOf('critical') > 0) {
              classes.push('table-danger');
          }
          return classes;
      },
~~~

**Comment by linmasahiro** [comment]
Hi, @alexey-us 
Thanks your advice, I am already added the feature, but not only typeof function, can will be typeof array too. Please check [document](https://linmasahiro.github.io/vue3-table-lite/dist/api.html#props).

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
