### ISSUE TITLE
Suggestion to add selected item event 

### ISSUE THREAD

**Issue by JuanGuillenMartinez** [linmasahiro/vue3-table-lite#39]
I would like to suggest the option of adding an event called "selected" to manipulate the records that are selected within the table. It would look like this.
```
<tr
       @click="$emit('selected', row)"
        v-for="(row, i) in rows"
        :key="i"
        class="vtl-tbody-tr"
        :class="typeof rowClasses === 'function' ? rowClasses(row) : rowClasses"
>
```
Both the static and dynamic tables should include this event as it is very useful.

**Comment by linmasahiro** [comment]
Hi, @JuanGuillenMartinez 
Your means want a event for `callback after click anywhere in <tr>`?

**Comment by linmasahiro** [comment]
#41

**Comment by linmasahiro** [comment]
Hi @JuanGuillenMartinez 
Maybe you can check issue #41, hope it is you want feature.

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
