### ISSUE TITLE
Add types to TS

### ISSUE THREAD

**Issue by sebastianPeralta-alternova** [linmasahiro/vue3-table-lite#4]
I currently work Vue table lite in TS and present error as it doesn't have types

**Comment by linmasahiro** [comment]
> I currently work Vue table lite in TS and present error as it doesn't have types

OK,  supported on the ver1.0.4, update to ver1.0.4 plz.

**Comment by linmasahiro** [comment]
I am closing this issue. If you still have problem, reopen the issue.

**Comment by johnmasson** [comment]
Where are the type declarations, or how to get them? Installing 1.0.6 doesn't install any type definitions, and npm i --save-dev @types/vue3-table-lite can't find any either. Also tried with 1.0.4 with the same results.

**Comment by linmasahiro** [comment]
> Where are the type declarations, or how to get them? Installing 1.0.6 doesn't install any type definitions, and npm i --save-dev @types/vue3-table-lite can't find any either. Also tried with 1.0.4 with the same results.

If you install it from `npm i vue3-table-lite --save-dev`, you haven't need any type definitions files.
Because it's already compiled.

So I tried to created a new project and installed it.
```
$ npm init vite@latest my-vue-app -- --template vue
$ cd my-vue-app
$ npm i vue3-table-lite --save-dev
$ npm run dev
```

And push `import TableLite from "vue3-table-lite";` to App.vue 
```
<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <HelloWorld msg="Hello Vue 3 + Vite" />
  <TableLite />
</template>

<script setup>
import HelloWorld from './components/HelloWorld.vue'
import TableLite from "vue3-table-lite";

// This starter template is using Vue 3 experimental <script setup> SFCs
// Check out https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md
</script>
```

It's work good.

**Comment by hspaay** [comment]
Hi, I'm looking forward using this lightweight table, however this issue is still alive.

Using yarn and adding with `yarn add -D vue3-table-lite` adds it to the devDependencies in package.json but import fails with the same missing types error (using vite as a builder btw). This is with version 1.0.9.

**Comment by linmasahiro** [comment]
Hi @hspaay 
I am created a new typescript project and install `vue3-table-lite v1.0.9` by Vite.
I add `declare module "vue3-table-lite"` to `env.d.ts` only, and it's good working.
This is my install command and HelloWorld.vue.
```
$ npm init vite@latest
��� Project name: ��� vite-project
��� Select a framework: ��� vue
��� Select a variant: ��� vue-ts

Scaffolding project in /Users/lin/Sites/vue/vite_pj/vite-project...

Done. Now run:

  cd vite-project
  npm install
  npm run dev

$ cd vite-project 
$ npm i vue3-table-lite --save-dev
$ vi src/env.d.ts
```
Add `declare module "vue3-table-lite"` to `env.d.ts`, and edit default HelloWorld.vue

HelloWorld.vue:
```
<script setup lang="ts">
import { ref, reactive } from "vue";
import TableLite from "vue3-table-lite";

defineProps<{ msg: string }>();

const count = ref(0);

const sampleData1 = (offst: number, limit: number) => {
  offst = offst + 1;
  let data = [];
  for (let i = offst; i <= limit; i++) {
    data.push({
      id: i,
      name: "TEST" + i,
      email: "test" + i + "@example.com",
    });
  }
  return data;
};

const sampleData2 = (offst: number, limit: number) => {
  let data = [];
  for (let i = limit; i > offst; i--) {
    data.push({
      id: i,
      name: "TEST" + i,
      email: "test" + i + "@example.com",
    });
  }
  return data;
};

const table = reactive({
  isLoading: false,
  isReSearch: false,
  columns: [
    {
      label: "ID",
      field: "id",
      width: "3%",
      sortable: true,
      isKey: true,
    },
    {
      label: "Name",
      field: "name",
      width: "10%",
      sortable: true,
    },
    {
      label: "Email",
      field: "email",
      width: "15%",
      sortable: true,
    },
  ],
  rows: sampleData1(0, 10),
  totalRecordCount: 20,
  sortable: {
    order: "id",
    sort: "asc",
  },
  messages: {
    pagingInfo: "Showing {0}-{1} of {2}",
    pageSizeChangeLabel: "Row count:",
    gotoPageLabel: "Go to page:",
    noDataAvailable: "No data",
  },
});

const doSearch = (offset: number, limit: number, order: string, sort: string) => {
  table.isLoading = true;
  setTimeout(() => {
    table.isReSearch = offset == undefined ? true : false;
    if (offset >= 10 || limit >= 20) {
      limit = 20;
    }
    if (sort == "asc") {
      table.rows = sampleData1(offset, limit);
    } else {
      table.rows = sampleData2(offset, limit);
    }
    table.totalRecordCount = 20;
    table.sortable.order = order;
    table.sortable.sort = sort;
  }, 600);
};

const tableLoadingFinish = (elements: Array<HTMLElement>) => {
  table.isLoading = false;
  Array.prototype.forEach.call(elements, function (element: HTMLElement) {
    if (element.classList.contains("name-btn")) {
      element.addEventListener("click", function () {
        console.log(this.dataset.id + " name-btn click!!");
      });
    }
  });
};

const updateCheckedRows = (rowsKey: number) => {
  console.log(rowsKey);
};
</script>

<template>
  <div>
    <TableLite
      :has-checkbox="true"
      :is-loading="table.isLoading"
      :is-re-search="table.isReSearch"
      :columns="table.columns"
      :rows="table.rows"
      :total="table.totalRecordCount"
      :sortable="table.sortable"
      :messages="table.messages"
      @do-search="doSearch"
      @is-finished="tableLoadingFinish"
      @return-checked-rows="updateCheckedRows"
    />
  </div>
  <h1>{{ msg }}</h1>

  <p>
    Recommended IDE setup:
    <a href="https://code.visualstudio.com/" target="_blank">VSCode</a>
    +
    <a href="https://github.com/johnsoncodehk/volar" target="_blank">Volar</a>
  </p>

  <p>See <code>README.md</code> for more information.</p>

  <p>
    <a href="https://vitejs.dev/guide/features.html" target="_blank"> Vite Docs </a>
    |
    <a href="https://v3.vuejs.org/" target="_blank">Vue 3 Docs</a>
  </p>

  <button type="button" @click="count++">count is: {{ count }}</button>
  <p>
    Edit
    <code>components/HelloWorld.vue</code> to test hot module replacement.
  </p>
</template>

<style scoped>
a {
  color: #42b983;
}

label {
  margin: 0 0.5em;
  font-weight: bold;
}

code {
  background-color: #eee;
  padding: 2px 4px;
  border-radius: 4px;
  color: #304455;
}
</style>
```

**Comment by linmasahiro** [comment]
Hi @hspaay 

> Unfortunately it adds approx 120K to the bundle size... probably because the bundle now includes "compiler-core.esm-bundler.js"

I am removed Vue Dependency at bundle, so the bundle will not bundle `compiler-core.esm-bundler.js` now. Please upgrade to version 1.1.0.

![SampleGif](https://upload.cc/i1/2021/11/27/GBJLRu.jpg)

**Comment by Zersty** [comment]
I think this broke non typescript support
I don't use TS in my project and I can no longer build using 1.1.0

**Comment by linmasahiro** [comment]
> I think this broke non typescript support
I don't use TS in my project and I can no longer build using 1.1.0

Hi Alex, Your means you can't build on your TypeScript project on v1.1.0?
...I don't know why, because I use vite created my TypeScript project and install v1.1.0, it's working...

**Comment by Zersty** [comment]
No I don't have a typescript project,
I have a normal javascript project,
which now breaks because I do not have typescript

**Comment by linmasahiro** [comment]
> No I don't have a typescript project, I have a normal javascript project, which now breaks because I do not have typescript

OK...,I know I made a serious mistake, I am changed import file. Can you update to v1.1.2 and try it work or not work on your javascript project?
