### ISSUE TITLE
Request Event, Row Click event

### ISSUE THREAD

**Issue by teguhsatria892** [linmasahiro/vue3-table-lite#41]
please add row click event, this is more important feature for every table lib

**Comment by linmasahiro** [comment]
> please add row click event, this is more important feature for every table lib

Hi, @teguhsatria892 
Thanks for your request. I will be add the feature to next version.

**Comment by linmasahiro** [comment]
Hi, @teguhsatria892 
I am already added new event to catch row click event.
Check [this example](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/RowClicked.vue) to learn how to use it.

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
