### ISSUE TITLE
Request Style, Many Column

### ISSUE THREAD

**Issue by teguhsatria892** [linmasahiro/vue3-table-lite#43]
please add configuration to many column can scrollable to right

**Comment by linmasahiro** [comment]
Hi, @teguhsatria892 !
I added option for fixed first column on horizontal scrolling.
You can check [example](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/FixedFirstColumn.vue). 
And I closed this issue. If any questions, reopen it. thx.
