### ISSUE TITLE
Width not working well on 1.2.0

### ISSUE THREAD

**Issue by teguhsatria892** [linmasahiro/vue3-table-lite#44]
i set width to 500px and didnt change anything

![image](https://user-images.githubusercontent.com/53621652/167419436-2c292035-3b1c-4a59-bcf8-167c3129bb9e.png)

please fix this issue

**Comment by linmasahiro** [comment]
Hi, @teguhsatria892 

> i set width to 500px and didnt change anything
> please fix this issue

This is not bug, it is CSS feature. If you want fixed 500px, you need give it more space for table.
I am created example to explain it. 
[https://jsfiddle.net/na9tbzur/](https://jsfiddle.net/na9tbzur/)

**Comment by linmasahiro** [comment]
Hi, I closed this issue. If any questions, reopen it. thx.
