### ISSUE TITLE
Hidden Column

### ISSUE THREAD

**Issue by nosizejosh** [linmasahiro/vue3-table-lite#52]
Hey @linmasahiro is it possible to have a hidden column? 
A column that is not visible in the table but whose data can be used in a v-slot for example.
This will prevent the need for hitting the server api again just to get details for example which 
I want in a hover over my summary field. Details is not shown in the Table columns but that data should be available to be used.

**Comment by linmasahiro** [comment]
> Hey @linmasahiro is it possible to have a hidden column? A column that is not visible in the table but whose data can be used in a v-slot for example. This will prevent the need for hitting the server api again just to get details for example which I want in a hover over my summary field. Details is not shown in the Table columns but that data should be available to be used.

Yes, and very easy, don't add to `table.columns` only.

```
  <table-lite
    :is-static-mode="true"
    ...
  >
    <template v-slot:summary="data">
      <span>{{ data.value.aaa }}</span>
    </template>
  </table-lite>

......

    // This is your data from API
    const data = reactive([]);
    for (let i = 0; i < 126; i++) {
      data.push({
        id: i,
        summary: "TEST" + i,
        aaa: "Hidden" + i
      });
    }

    // Table config
    const table = reactive({
      columns: [
        {
          label: "ID",
          field: "id",
          width: "3%",
          sortable: true,
          isKey: true,
        },
        {
          label: "Summary",
          field: "summary",
          width: "10%",
          sortable: true,
        },
      ],
      ......
    });

......
```
