### ISSUE TITLE
Request grouping

### ISSUE THREAD

**Issue by RaskaTheFurry** [linmasahiro/vue3-table-lite#53]
Hello,

Is it possible to add groups to the table, where rows would be grouped by some identifier ( name of the group )?

**Comment by linmasahiro** [comment]
Hi @RaskaTheFurry 
Sorry, not support groups or sub-table yet, but it's interesting, have any example?

**Comment by RaskaTheFurry** [comment]
Hello,

Will a screenshot be enough as an example or should I make some demo page ?

This is one of the ways it could look.
![image](https://user-images.githubusercontent.com/43683045/180726157-8f201cac-dc73-4b97-9ef8-43405d7334f9.png)

**Comment by linmasahiro** [comment]
> Hello,
> 
> Will a screenshot be enough as an example or should I make some demo page ?
> 
> This is one of the ways it could look. 

Thanks your screenshot, I will be think how to add the feature into next version.

**Comment by linmasahiro** [comment]
Hi, @RaskaTheFurry 
I already add grouping feature into v1.2.4, so maybe you can try it follow this [example1](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/Grouping2.vue) [example2](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/Grouping.vue)

**Comment by linmasahiro** [comment]
Hi, @RaskaTheFurry 
do you solve this problem? I am close this issue. If any questions, reopen it. thx.
