### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by giuliaSan** [linmasahiro/vue3-table-lite#54]
I'm loading a simple API with a list of name/description.
Sorting the rows by name doesn't work, asc or desc, they are always in the same order

**Comment by linmasahiro** [comment]
Hi @giuliaSan 
Maybe you can paste the code or more details?

**Comment by RaskaTheFurry** [comment]
Do you use @do-search ?
If its call to API, then it shouldnt really be used for sorting data by itself, but rather make call to API to get data sorted in the format you want as @do-search gives you orderBy ( order ) and order ( sort ) ( plus top and skip )
Thats how we use it and it seems to work fine.

**Comment by linmasahiro** [comment]
Add `@do-search` will be resolve the problem.
Updated `@do-search`'s description in document.
