### ISSUE TITLE
Table sort is not working.

### ISSUE THREAD

**Issue by sozboke** [linmasahiro/vue3-table-lite#55]
The sort feature in this, sometimes works, sometimes not also I tried your demo code in my my code, it also works sometimes, sometimes not. Could you fix and stabilize this feature?

**Comment by linmasahiro** [comment]
Hi @sozboke 
I am tried in my demo code and my production service, sorting is good working, so I don't know why.
More detail or your code please. (default-mode or static-mode...etc)

same problem : #54

**Comment by sozboke** [comment]
I found the problem @linmasahiro if you don't add the @do-search annotation sort feature is not working. Also clicking sort triggers @do-search event. So you should write that down in the documentation. Thank you for the table have a nice day :)
