### ISSUE TITLE
Refresh page after delete row

### ISSUE THREAD

**Issue by roke22** [linmasahiro/vue3-table-lite#56]
Hello,

How can i refresh the table data without losing all filters and page position? There is a way to get the offset and limit values to do the same request. I am using the ajax request to get the data.

Thank you.

**Comment by linmasahiro** [comment]
Hi @roke22 
> How can i refresh the table data without losing all filters and page position? There is a way to get the offset and limit values to do the same request. I am using the ajax request to get the data.

Thanks your question. I am knew your trouble, I thought how to resolve about this trouble, and try to add an option to keep paging, but it's not good solution.
Because if you keep the search conditions ( include paging), maybe will be get null response.
Like you using ajax to get 31 records, and 10 records per page. And you choose to Page.4 and delete last record.
Next, if you keep the paging, maybe you will be get error, because you will be request offset 31 ~ 40 records, right?

**Comment by roke22** [comment]
I understand you but the client/user only wants to remove a record and view that the records dissapears. That from the point of view of the final user.

Maybe you have to control if the page exist and if not exists refresh again with one page less until you get data. Can be possible??

Thank you.
Sorry for my bad english :(

**Comment by linmasahiro** [comment]
> I understand you but the client/user only wants to remove a record and view that the records dissapears. That from the point of view of the final user.

Hi, @roke22 
If you really hope to keep the paging, in fact, has a method, use `Static-mode` please.
I am wrote an example for you, and you need rewrite delete Request function to really AJAX only.
Hope to helpful you.

```
<template>
  <table-lite
    :is-loading="table.isLoading"
    :is-static-mode="true"
    :columns="table.columns"
    :rows="table.rows"
    :total="table.totalRecordCount"
    :sortable="table.sortable"
    @is-finished="tableLoadingFinish"
  ></table-lite>
</template>

<script>
import { defineComponent, reactive, computed } from "vue";
import TableLite from "../components/TableLite.vue";

export default defineComponent({
  name: "App",
  components: { TableLite },
  setup() {
    // Fake data
    let data = reactive([]);
    for (let i = 0; i < 126; i++) {
      data.push({
        id: i,
        name: "TEST" + i,
        email: "test" + i + "@example.com",
      });
    }

    // Table config
    const table = reactive({
      isLoading: false,
      columns: [
        {
          label: "ID",
          field: "id",
          width: "3%",
          sortable: true,
          isKey: true,
        },
        {
          label: "Name",
          field: "name",
          width: "10%",
          sortable: true,
        },
        {
          label: "Email",
          field: "email",
          width: "15%",
          sortable: true,
        },
        {
          label: "",
          field: "",
          width: "15%",
          sortable: false,
          display: function (row) {
            return (
              "<button class='is-rows-el delete-btn' data-id='" +
              row.id +
              "'>DELETE</button>"
            );
          },
        },
      ],
      rows: data,
      totalRecordCount: computed(() => {
        return table.rows.length;
      }),
      sortable: {
        order: "id",
        sort: "asc",
      },
    });

    const tableLoadingFinish = (elements) => {
      table.isLoading = false;
      Array.prototype.forEach.call(elements, function (element) {
        if (element.classList.contains("delete-btn")) {
          element.addEventListener("click", function (event) {
            event.stopPropagation(); // prevents further propagation of the current event in the capturing and bubbling phases.
            deleteRequest(this.dataset.id);
          });
        }
      });
    };

    const deleteRequest = (id) => {
      table.isLoading = true;
      setTimeout(() => {
        let index = data.findIndex((v) => v.id == id);
        if (index >= 0) {
          data.splice(index, 1);
        }
        table.rows = data;
        table.isLoading = false;
      }, 1000);
    };

    return {
      table,
      tableLoadingFinish,
    };
  },
});
</script>
```

**Comment by linmasahiro** [comment]
Hi, @roke22 
do you solve this problem? I am close this issue. If any questions, reopen it. thx.
