### ISSUE TITLE
is-fixed-first-column issue

### ISSUE THREAD

**Issue by lunu5** [linmasahiro/vue3-table-lite#59]
The first cell of the first column is overlapped by the first column when scrolling vertically and by the first row when scrolling horizontally

**Comment by linmasahiro** [comment]
HI, @lunu5 
Sorry, I am checked scrolling horizontally and it's working good, so I don't know what's problem, can you capture a screen for me?
Thx :)

**Comment by lunu5** [comment]
The first image is when no scrolling
<img width="302" alt="image" src="https://user-images.githubusercontent.com/80402166/193491410-26d094bb-0fb6-4a2a-b9e4-aca40b32b334.png">
The second image is when scrolling vertically
<img width="301" alt="image" src="https://user-images.githubusercontent.com/80402166/193491967-0653a805-66e8-42bc-94f8-387a1e2369a3.png">
The third image is when scrolling horizontally
<img width="218" alt="image" src="https://user-images.githubusercontent.com/80402166/193491861-66ae6e79-f819-4125-99b6-201900c26491.png">
The last one is both
<img width="251" alt="image" src="https://user-images.githubusercontent.com/80402166/193492550-cdc32948-a29a-471d-b201-bf57d7ace426.png">

**Comment by linmasahiro** [comment]
@lunu5 , thanks for your captures.
I saw your header's first-column not show. Are you customize stylesheet to fixed the header on scrolling vertically? (ex. position: fixed or absolute?)
Maybe that is the reason why, don't adjust header's position, it will be affect to this feature.

**Comment by linmasahiro** [comment]
@lunu5 , I am try to add new option for fixed table header to solve this problem, so please wait.

**Comment by linmasahiro** [comment]
Hi, @lunu5 , I add `max-height` prop to set table's height and fixed the bug, thanks for your issue 👍 
Here an [example](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/FixedHeaderAndFirstColumn.vue) , please check it!

**Comment by lunu5** [comment]
Thanks for your support
