### ISSUE TITLE
Loading mask hides Vuetify v-app-bar

### ISSUE THREAD

**Issue by roelofsaj** [linmasahiro/vue3-table-lite#63]
I'm using this with vuetify 3, and the z-index of the table loading mask here is higher than the z-index of vuetify's v-app-bar, so the loading mask overlays the app menu bar. It seems like this should be the other way around; see screenshots below.

Current behavior (note that one of the menu items is inaccessible behind the loading mask):
<img width="532" alt="Screen Shot 2022-11-07 at 11 27 05 AM" src="https://user-images.githubusercontent.com/14942055/200363840-08869790-ac5d-4e86-862c-e8d71cca02b8.png">

Desired behavior:
<img width="532" alt="Screen Shot 2022-11-07 at 11 29 55 AM" src="https://user-images.githubusercontent.com/14942055/200363856-6211c536-bf5a-449c-8c2d-890ff0f2cf64.png">

**Comment by linmasahiro** [comment]
Hi, @roelofsaj , very thanks for your pull request!!
Set z-index level to than 3 and it's good working, so I am reseted value to 3.
