### ISSUE TITLE
Select all checkbox does not check if all checkboxes in the table row are checked

### ISSUE THREAD

**Issue by lloyde04102000** [linmasahiro/vue3-table-lite#66]
Hello,
Is there a way to make the select all checkbox in the header checked without clicking it if all checkboxes in the table rows are checked?
![Screenshot 2022-12-06 115712](https://user-images.githubusercontent.com/75734956/205809596-8920f2c0-8648-40b7-8f06-efeb7e12e1e3.png)

**Comment by linmasahiro** [comment]
> Hello, Is there a way to make the select all checkbox in the header checked without clicking it if all checkboxes in the table rows are checked? ![Screenshot 2022-12-06 115712](https://user-images.githubusercontent.com/75734956/205809596-8920f2c0-8648-40b7-8f06-efeb7e12e1e3.png)

Hi, @lloyde04102000 
Yes, you can reference this example to implement it.
```
<template>
  <button @click="doCheckedAll">Checked all</button>
  <table-lite
    ref="tableLiteRef"
    :has-checkbox="true"
    ...something...
    @return-checked-rows="updateCheckedRows"
  ></table-lite>
</template>
<script>
    // ...something

    const tableLiteRef = ref();
    const doCheckedAll = () => {
      tableLiteRef.value.setting.isCheckAll = true
    }

    return {
      // ...something
      tableLiteRef,
      doCheckedAll,
    };
</script>
```

**Comment by lloyde04102000** [comment]
Thank You for your response @linmasahiro. This is good. However, if the header select-all checkbox is checked, then if I am going to uncheck one of the checkboxes in the table row, it remains checked. Can we do something about it?

**Comment by linmasahiro** [comment]
>However, if the header select-all checkbox is checked, then if I am going to uncheck one of the checkboxes in the table row

It's easy, delete `tableLiteRef.value.setting.isCheckAll = true` and add
```
tableLiteRef.value.rowCheckbox.forEach(element => {
  element.checked = true;
});
```
to `doCheckedAll `, it's to checked all checkboxes but  header select-all checkbox not to active.

**Comment by linmasahiro** [comment]
Hi, @lloyde04102000  , is this issue resolved now? :)
