### ISSUE TITLE
Two Grouping feature requests

### ISSUE THREAD

**Issue by dandoteverest** [linmasahiro/vue3-table-lite#67]
Hello,

I noticed Grouping is rather new, and was wondering if you could add 2 features to it:

1. a flag to render the table with all rows collapsed (e.g., start-collapsed="true")
2. an event when the row is expanded and collapsed, or a toggle event with the state of the row (e.g., emit("row-toggled", row, collapsedOrExpanded))

I want to use the grouping feature to limit the data pulled from our servers, and essentially make an Ajax call upon expanding a row.

Thanks!

**Comment by dandoteverest** [comment]
Thanks for the quick turn around! However, I've noticed an issue for the way I intend to use this feature. As I mentioned above, I will be populating the expanded rows using an ajax call and replacing rows upon successful data load. But it seems that every time I replace data, the table refreshes, which then collapses all of the rows (due to the new 'startCollapsed' flag). So while the rows are there, they can't be viewed, because each time I expand, I load new data, which refreshes...etc

I wrote a fiddle here that shows what I'm trying to do:
https://codesandbox.io/s/quizzical-robinson-rh7u66?file=/src/App.vue

And yes, I intended to keep the 'debugger' statement in the 'tableLoadingFinish'. If you load the debugger, you'll see during the breakpoint the rows are expanded, and when you continue, it collapses again.

**Comment by linmasahiro** [comment]
> But it seems that every time I replace data, the table refreshes, which then collapses all of the rows (due to the new 'startCollapsed' flag). So while the rows are there, they can't be viewed, because each time I expand, I load new data, which refreshes...etc

OK, I am knew the problem.
So, If I will be add an option(ex: is-keep-collapse-status) to keep the collapses status, and it can resolve all collapsed after refresh data or paging.
How do you think about this solution?

**Comment by dandoteverest** [comment]
That should work, provided it doesn't re-emit the toggle event (or else we'll end up in an infinite loop...).

**Comment by linmasahiro** [comment]
> That should work, provided it doesn't re-emit the toggle event (or else we'll end up in an infinite loop...).

OK, I added `is-keep-collapsed` option and published `v1.2.9`.  Upgrade to `v1.2.9` and [check the example](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/Grouping.vue) please.

**Comment by linmasahiro** [comment]
Hi, @dandoteverest  , is this issue resolved now? :)

**Comment by dandoteverest** [comment]
Yes, that seemed to fix the issue.Thanks! I'll close this out.
