### ISSUE TITLE
selected rows are not updated immediately after rows are updated

### ISSUE THREAD

**Issue by alexandrei892** [linmasahiro/vue3-table-lite#68]
I'm having some troubles selecting newly added rows to the table, immediately after `@do-search="doSearch"` is called.
If I click the "select all" once or twice, it's fine, or if I refresh the tab. 
But immediately after refresh, if I select the new row, after the `rowsKey` array is filled with `undefined`.

```
<TableLite
        :is-slot-mode="true"
        :has-checkbox="true"
        :is-loading="table.isLoading"
        :columns="table.columns"
        :rows="table.rows"
        :total="table.totalRecordCount"
        :sortable="table.sortable"
        :page="table.page"
        :is-keys="true"
        :checked-return-type="row"
        :tableType="table.tableType"
        class="clear-both"
        @get-now-page="getCurrentPage"
        @do-search="doSearch"
        @is-finished="tableLoadingFinish"
        @return-checked-rows="getCheckedRows"
    >
```

```
const table = reactive({
  isLoading: false,
  tableType: 'main',
  columns: [
    { 
    // ... column definition ...
    }
  ],
  rows: [],
  selectedRows: [],
  page: 1,
  totalRecordCount: 0,
  sortable: {
    order: "id",
    sort: "desc",
  }
});
```

```
const getCheckedRows = (rowsKey: any) => {
  console.log(rowsKey);
  table.selectedRows = rowsKey;
  console.log(rowsKey, table.selectedRows);
}

const doSearch = (offset: number, limit: number, order: string, sort: string) => {
  offsetValue = offset;
  limiteValue = limit;
  table.isLoading = true;

  apiGetData(offset, limit, order, sort, searchTerm.value).then((response: any) => {
    table.rows = response.data.data;
    table.totalRecordCount = response.data.meta.total;
    table.sortable.order = order;
    table.sortable.sort = sort;
  })
};

const apiGetData = (offset: number, limit: number, order: string, sort: string, search: string) => {
  let url = `http://localhost/endpoint`;

  return axios.get(url,
      {
        params: {
          offset: offset,
          limit: limit,
          sortBy: order,
          sortType: sort,
          search: search
        }
      });
}

const refreshTable = () => {
  doSearch(offsetValue, limiteValue, table.sortable.order, table.sortable.sort);
}
```

Console output here
select all, first click, selects all items on the page
```
(10) [Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, undefined]
(10) [Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, undefined] Proxy {0: Proxy, 1: Proxy, 2: Proxy, 3: Proxy, 4: Proxy, 5: Proxy, 6: Proxy, 7: Proxy, 8: Proxy, 9: undefined}
```

select all, second click, deselects all items
select all, third click, selects all items

```
(10) [Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy]
(10) [Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy] Proxy {0: Proxy, 1: Proxy, 2: Proxy, 3: Proxy, 4: Proxy, 5: Proxy, 6: Proxy, 7: Proxy, 8: Proxy, 9: Proxy}
```

**Comment by linmasahiro** [comment]
Hi, @alexandrei892 
I used your source code to created an example on `codesandbox`, but it's good working, so I don't know what happened...
Can you create a demo for me?

[https://codesandbox.io/s/bitter-night-6m0ydn?file=/src/components/Table.vue](https://codesandbox.io/s/bitter-night-6m0ydn?file=/src/components/Table.vue)

**Comment by alexandrei892** [comment]
Hi and thanks for the super quick reply :)
In your demo, on page 1, if you check one or two checkboxes, it will display just fine in the console, `[Object, Object]`
But if you go to page 2, and check one or two checkboxes, you will see this `[undefined, undefined, undefined]`

**Comment by linmasahiro** [comment]
Hi, @alexandrei892 
Thanks your response, I fixed the bug and released v1.3.0, upgrade please. :)

https://codesandbox.io/s/bitter-night-6m0ydn?file=/src/components/Table.vue

**Comment by ManuelTS** [comment]
Thanks a lot @linmasahiro, but shoudn't this issue be closed too then?

**Comment by linmasahiro** [comment]
Hi, @ManuelTS 

> Thanks a lot @linmasahiro, but shoudn't this issue be closed too then?

Is This issue resolve?  OK, I am close this issue, if any question reopen please.
