### ISSUE TITLE
Unchecking rows(s)

### ISSUE THREAD

**Issue by dandoteverest** [linmasahiro/vue3-table-lite#71]
Hi,

I was wondering if it's possible to programactically 'uncheck' a row (or set of rows). Or, better yet, only allow a single row checked per a group if grouping rows?

Thanks!

**Comment by linmasahiro** [comment]
Hi, @dandoteverest 

> I was wondering if it's possible to programactically 'uncheck' a row (or set of rows). Or, better yet, only allow a single row checked per a group if grouping rows?

Yes, you can get the table's reference object to trigger checkbox's click event.
Here has an example
```
<template>
  <button @click="triggerCheckboxEvent(0)">triggerCheckboxEvent</button>
  <table-lite
    ref="tableRef"
    :has-checkbox="true"
    ...
  ></table-lite>
</template>

<script>
    // ... something

    const tableRef = ref(null);
    const triggerCheckboxEvent = (index) => {
      tableRef.value.rowCheckbox[index].click();
    }

    return {
        // ... something
        tableRef,
        triggerCheckboxEvent
    }
</script>
```

**Comment by linmasahiro** [comment]
#83

**Comment by linmasahiro** [comment]
Is it resolved? If not, reopen please.
