### ISSUE TITLE
Multiple fixed columns

### ISSUE THREAD

**Issue by RaskaTheFurry** [linmasahiro/vue3-table-lite#72]
Hello,

Is it possible to change is-fixed-first-column into multiple columns, not just the first one? Maybe something like has-fixed-columns and then add prop, that will be a number of columns, that should be fixed?

**Comment by linmasahiro** [comment]
Hi @RaskaTheFurry 
Thanks for your request, but I don't know how to scroll at `fixed multiple columns`.
If you has any example(gif, jpg...etc), please give me, thx.

**Comment by RaskaTheFurry** [comment]
Hi @linmasahiro 
ofc, I was given these exmaples:
https://dev.to/nicolaserny/table-with-a-fixed-first-column-2c5b
https://codepen.io/nicolaserny/pen/zYEqgVv

But instead of just 1 column being fixed, we would need N-number of columns fixed.

**Comment by linmasahiro** [comment]
Hi, @RaskaTheFurry 
> But instead of just 1 column being fixed, we would need N-number of columns fixed.

If you want to implement the example only, you can use `::v-deep` to control style like this code will be fixed 3 columns on scrolling,
```
<style scoped>
::v-deep(.vtl-table tbody tr td:nth-child(1)),
::v-deep(.vtl-table .vtl-thead th:nth-child(1)) {
  position: sticky;
  left: 0;
  z-index: 2;
}
::v-deep(.vtl-table tbody tr td:nth-child(2)),
::v-deep(.vtl-table .vtl-thead th:nth-child(2)) {
  position: sticky;
  left: 71.5px;
  z-index: 2;
}
::v-deep(.vtl-table tbody tr td:nth-child(3)),
::v-deep(.vtl-table .vtl-thead th:nth-child(3)) {
  position: sticky;
  left: 172px;
  z-index: 2;
}
</style>
```

**Comment by linmasahiro** [comment]
Is it resolved? If not, reopen please.
