### ISSUE TITLE
Sortable function doesn't work with grouping key

### ISSUE THREAD

**Issue by GiuseppeSperanza** [linmasahiro/vue3-table-lite#76]

**Comment by linmasahiro** [comment]
Hi @GiuseppeSperanza , I created an example and it's good working. So, I don't know your problem, more details please.
https://codesandbox.io/s/bitter-night-6m0ydn?file=/src/components/Table.vue

**Comment by linmasahiro** [comment]
Is it resolved? If not, reopen please.
