### ISSUE TITLE
checking rows doesn't work in 1.3.2 and 1.3.3

### ISSUE THREAD

**Issue by alexandrei892** [linmasahiro/vue3-table-lite#78]
Clicking on the checkbox for a row does not select it, clicking repeatedly will select all checkboxes. 
This is reproducible in [the official demo](https://vue3-lite-table.vercel.app/advance-examples#customize-display-data)
In my particular case (1.3.3), if I click repeatedly after all rows have been selected, the row I click on is being duplicated.

**Comment by linmasahiro** [comment]
@alexandrei892 fixed on v1.3.4
