### ISSUE TITLE
click event not handled in tableLoadingFinish function

### ISSUE THREAD

**Issue by cams03** [linmasahiro/vue3-table-lite#80]
Hello @linmasahiro ,

according to your example to display cutsomize data I did this : 
![image](https://user-images.githubusercontent.com/23052324/220142580-2ea1c911-8bf0-4933-bb54-dbd49a02a39d.png)

![image](https://user-images.githubusercontent.com/23052324/220143435-fb9177d6-1e35-40ad-978f-6bbc9450c825.png)

But nothing happens when I click on my element with "edit" className, not even an error in the console

Can you help me finding what's wrong please ?

**Comment by linmasahiro** [comment]
Hi @cams03 

> But nothing happens when I click on my element with "edit" className, not even an error in the console
> Can you help me finding what's wrong please ?

Yes, please add `is-rows-el` class to your div element, has description in [`is-finished` event document](https://vue3-lite-table.vercel.app/api-reference#events)

**Comment by cams03** [comment]
> Hi @cams03
> 
> > But nothing happens when I click on my element with "edit" className, not even an error in the console
> > Can you help me finding what's wrong please ?
> 
> Yes, please add `is-rows-el` class to your div element, has description in [`is-finished` event document](https://vue3-lite-table.vercel.app/api-reference#events)
> 
> ※ You can check [this row](https://github.com/linmasahiro/vue3-table-lite/blob/master/src/examples/CustomizeDisplayData.vue#L80) too

Hi ! Ooow ok I missed that point, it works now ! Thanks for your help !
