### ISSUE TITLE
Bug when dynamically showing checkboxes

### ISSUE THREAD

**Issue by dandoteverest** [linmasahiro/vue3-table-lite#85]
If I have a table that initially does not have checkboxes, and I dynamically show them, the table dies a horrible death when re-rendering. Conversely, when I start out with checkboxes, then toggle back & forth between hiding & showing, it works fine.

I wrote a quick example here:
https://codesandbox.io/s/hide-checkbox-rh7u66?file=/src/App.vue

Scroll down to the bottom of the example and change the initial value of 'showCheckboxes' to see both cases.

**Comment by linmasahiro** [comment]
Hi @dandoteverest , Thanks for your issue, already fixed on v1.3.7.
