### ISSUE TITLE
Grouping with toggle like a treeview inside table ?

### ISSUE THREAD

**Issue by cams03** [linmasahiro/vue3-table-lite#86]
Hello @linmasahiro ,
I would like to know if it's possible tu use grouping with toggle to group by folder and create like a treeview inside the table ? Something like this : 
![image](https://user-images.githubusercontent.com/23052324/228840451-65e0bc06-a9fa-491f-b686-e28332af2953.png)

Thanks a lot for your help !

**Comment by cams03** [comment]
Hello, 

thanks you for your answer, I found another way, I built a treeview and put the table inside every child of the treeview, the issue is that the data is not updated in the table and I have the same lines in all the tables instead of having different data in every table, I put a watcher on table.rows and it receives the new data but doesn't update it in the table. Do you have an idea why or maybe a way to fix this ?
![image](https://user-images.githubusercontent.com/23052324/233012433-a79bac61-f550-47f9-be9c-1e5757a461ad.png)

**Comment by linmasahiro** [comment]
Hi, @cams03 
Is it resolved? If not, reopen please.
