### ISSUE TITLE
[OTHERS] Call a Function inside of display property for a button

### ISSUE THREAD

**Issue by at-the-vr** [linmasahiro/vue3-table-lite#87]
Hey Lin, love your project, can you help me understand how I can call a function inside a display attribute for a button without the Event Listener methods

![image](https://user-images.githubusercontent.com/88548999/231148208-971575d3-51fa-45ca-9f7b-931800cd1d74.png)
![image](https://user-images.githubusercontent.com/88548999/231148367-490a2aa9-0dbb-4899-842d-f7f4bacdb6fb.png)
 
I understand if my logRow method is wrong, but can you help me just call that method so that it can at least console log the entire row or even static data

**Comment by at-the-vr** [comment]
I missed to mention, the way I have written the logRow method right inside that button, that method is not getting triggered and I would just like to know if there's an approach to do that (Thanks again for hearing me)

**Comment by at-the-vr** [comment]
Hey Lin, in the current situation i believe i should go with v-slot mode, do you have an example possibly in options api for this mode ?

**Comment by at-the-vr** [comment]
Yeah that's what i did also my side, one thing, when i switch to v-slot mode, it broke the whole sorting process ( I am not using the do-search method)

**Comment by at-the-vr** [comment]
https://stackblitz.com/edit/vue-lwupnc?file=src/App.vue , can I ask if you can try running this app on stackblitz ? with following dependencies
![image](https://user-images.githubusercontent.com/88548999/231394579-4fc476b1-0c11-4d0a-8c47-faec3f85c520.png)

**Comment by linmasahiro** [comment]
> https://stackblitz.com/edit/vue-lwupnc?file=src/App.vue , can I ask if you can try running this app on stackblitz ? with following dependencies ![image](https://user-images.githubusercontent.com/88548999/231394579-4fc476b1-0c11-4d0a-8c47-faec3f85c520.png)

Your example is crash now, so I don't know why not working.
Maybe you can implement a simple sample your self first?

**Comment by at-the-vr** [comment]
> > https://stackblitz.com/edit/vue-lwupnc?file=src/App.vue , can I ask if you can try running this app on stackblitz ? with following dependencies ![image](https://user-images.githubusercontent.com/88548999/231394579-4fc476b1-0c11-4d0a-8c47-faec3f85c520.png)
> 
> Your example is crash now, so I don't know why not working. Maybe you can implement a simple sample your self first?

I have trimmed couple of markdown and css to reduce the overall length, can you give this another try ?

**Comment by linmasahiro** [comment]
> I have trimmed couple of markdown and css to reduce the overall length, can you give this another try ?

OK, it's working now.
I saw your example and find the bug.
You need add `:is-static-mode="true"` to `<table-lite>`, because you not use `do-search` to get any data.

**Comment by at-the-vr** [comment]
![image](https://user-images.githubusercontent.com/88548999/231415633-2da461c5-e8cf-49be-9996-adcb03598839.png)

Is this a bad way to produce my results (they are kinda working)

**Comment by linmasahiro** [comment]
if resolved, I will be close this issue :)

**Comment by at-the-vr** [comment]
I guess yeah, thanks for the slot stuff
