### ISSUE TITLE
Unchecking row returns old value

### ISSUE THREAD

**Issue by WordpressArtist** [linmasahiro/vue3-table-lite#89]
I have checked a row , got the checked row fine but when i unchecked the row its not removing the value, adding on checked but not removing on uncheck, Can you please help

<img width="593" alt="Screenshot 2023-05-10 at 09 21 07" src="https://github.com/linmasahiro/vue3-table-lite/assets/12960551/69753ab3-0938-48b1-998c-0fa9075a9536">

<img width="532" alt="Screenshot 2023-05-10 at 09 21 13" src="https://github.com/linmasahiro/vue3-table-lite/assets/12960551/0441451b-cd5b-4405-ac61-a28f3b78e875">

**Comment by WordpressArtist** [comment]
it keeps adding but not removing on uncheck , same  item adding multiple times 
<img width="498" alt="Screenshot 2023-05-10 at 09 26 12" src="https://github.com/linmasahiro/vue3-table-lite/assets/12960551/516ba234-3760-4573-91f4-972085db0601">

**Comment by linmasahiro** [comment]
Hi @WordpressArtist 
I can't implement this problem on latest version, more detail please.

**Comment by WordpressArtist** [comment]
I installed "vue3-table-lite": "^1.2.4"
 now i set up 
@return-checked-rows="onCheckRows"
 :checked-return-type="'id'"
 :has-checkbox="true"

now when i click on bulk check and uncheck works fine 
but when i check individual row, it logs. the value 
 
onCheckRows(rows) {
    conosle.log(rows)
}

but  when i uncheck, that the id must not be there but it still there.

Example:
i checked 1 row , please check log (i got 22 )
<img width="457" alt="Screenshot 2023-05-10 at 13 11 07" src="https://github.com/linmasahiro/vue3-table-lite/assets/12960551/ac224bd2-f994-4a4a-92eb-1fe3a49e3fd7">
Now uncheck the same item i can see still 22 on log
<img width="492" alt="Screenshot 2023-05-10 at 13 11 57" src="https://github.com/linmasahiro/vue3-table-lite/assets/12960551/4e13443f-922c-46f9-a44d-4914ca9ef82f">

now i check that item again i got 2 same data previous selected and current selected

<img width="414" alt="Screenshot 2023-05-10 at 13 12 41" src="https://github.com/linmasahiro/vue3-table-lite/assets/12960551/c2399935-7b7c-43e2-8f93-886fa6f03947">

Now if i uncheck it still same 2 datas 
if i again check it keeps adding item on array but not removing

**Comment by linmasahiro** [comment]
@WordpressArtist 
Thanks for your information, the bug already fixed after v1.3.0.
So, upgrade than  v1.3.0 up please.
