### ISSUE TITLE
Examples not compatible with latest version of vue3 and node18

### ISSUE THREAD

**Issue by Rednas83** [linmasahiro/vue3-table-lite#90]
I am not able to get the Filter3 example up and running.

Can you consider migrating to the latest version of vue3 and node18?

Tried it myself too but ran in it to all kinds of problems😬 
![image](https://github.com/linmasahiro/vue3-table-lite/assets/25219229/e3f524c9-a2b9-43fb-9723-377fa5524405)
![image](https://github.com/linmasahiro/vue3-table-lite/assets/25219229/bfc1379c-8d2d-4729-8925-25739b1261fc)

**Comment by linmasahiro** [comment]
Hi @Rednas83 
I am resolved the problem, if you will be use v5.0.8 to run the project, please fork [90-examples-not-compatible-with-latest-version-of-vue3-and-node18](https://github.com/linmasahiro/vue3-table-lite/tree/90-examples-not-compatible-with-latest-version-of-vue3-and-node18) branch.

※This is vue-cli version problem.  Upgrade your vue-cli to latest version and create new project, and move src folder to new project can resolved. If have any question, reopen please.
