### ISSUE TITLE
Vertical highlighting on mouse hover

### ISSUE THREAD

**Issue by Boardtale** [linmasahiro/vue3-table-lite#93]
We have 3x3. Hover mouse over [1][2] and highlighted cells would be with X if rows and columns higlithing is ON

[0][0][x]
[x][x][x]
[0][0][x]

**Comment by linmasahiro** [comment]
Hi, @Boardtale
Thanks for your request, I will be add the feature soon.

**Comment by linmasahiro** [comment]
Hi, @Boardtale , I already added vertical highlight options, please upgrade v1.3.9 and set `is-vertical-highlight="true"`.

**Comment by Boardtale** [comment]
Awesome to hear <3 Thank you! 
Already tested, works great
![image](https://github.com/linmasahiro/vue3-table-lite/assets/132870043/5bc3a0fd-5089-47d5-9bb4-8a10220675af)
