### ISSUE TITLE
has-checkbox and is-fixed-first-column turned on, only checkbox header stays when table scrolls horizontally.

### ISSUE THREAD

**Issue by georgemeng** [linmasahiro/vue3-table-lite#94]
Hello, 

Thanks for your project!

In my project, I have a multiple column table and have has-checkbox and is-fixed-first-column turned on the same time, I expect to keep first two columns and headers fixed when user scrolling to see the right columns.

You could see it from here: https://codesandbox.io/s/vue3-table-lite-forked-7mdykn?file=/src/App.vue

When I move the scrollbar to the right, the first two columns are fixed (checkbox column and first column) but only one header is fixed (the checkbox header), that is a little odd.

**Comment by linmasahiro** [comment]
Hi @georgemeng 
This bug already fixed on v1.3.1, so upgrade upper v1.3.1 please.

**Comment by georgemeng** [comment]
Thank you! Good to know that. I checked the version I used in the project, it was 1.2.6.

Will suggest the team to upgrade that. 

Thank you for your help!

**Comment by georgemeng** [comment]
Got the answer! Thanks! Closing the ticket.
