### ISSUE TITLE
[Vue warn]: Hydration node mismatch

### ISSUE THREAD

**Issue by Rednas83** [linmasahiro/vue3-table-lite#97]
When using `VueTableLite` with nuxt I get the following warning 
![image](https://github.com/linmasahiro/vue3-table-lite/assets/25219229/78aa3cf9-a2c6-405c-afd5-cb6a343a2d6c)
My call is
```
      <!-- Table -->
      <VueTableLite
        v-if="cindex.type == 'table'"
        :columns="cindex.header"
        :rows="cindex.items"
        :total="cindex.items?.length"
        :page-size="cindex.items?.length < 10 ? cindex.items?.length : 10"
        :sortable="inputs.sortable"
        :is-static-mode="true"
        :has-checkbox="inputs.selectable"
      ></VueTableLite>
```
With this data
![image](https://github.com/linmasahiro/vue3-table-lite/assets/25219229/e8eceb07-b35e-4140-a50a-0186a417d7ac)

The table loads fine, but I am not sure how to get rid of the warning? Any ideas?

**Comment by Rednas83** [comment]
Just tried it with `ClientOnly` but I still have the warning unfortunately
![image](https://github.com/linmasahiro/vue3-table-lite/assets/25219229/3b22d0ad-9329-46aa-9f00-c169d4e143a4)
Tried:
* Restarting the server
* Making it simpler also didn't work
`<VueTableLite :columns="cindex.header" :rows="cindex.items"></VueTableLite>`
* Using the website example worked without warning. Biggest different that I can see is that my data is asynchronously
 https://github.com/linmasahiro/vue3-table-lite#samplecode

**Comment by Rednas83** [comment]
Moving `ClientOnly` to the root instead of just `VueTableLite` caused an error instead of the warning
![image](https://github.com/linmasahiro/vue3-table-lite/assets/25219229/d67629c3-6302-49e5-9006-ab9877425ae9)
After turning off **static mode** it now works as expected

Any ideas why static mode is not working with nuxt? Perhaps I also don't need it

**Comment by linmasahiro** [comment]
Hi, @Rednas83 
It's nuxt3's project? Can you implement the problem on Codesandbox?

**Comment by Rednas83** [comment]
Just tried reproducing it with Sandbox but no problems there so I guess I will have to look further in my application.
https://codesandbox.io/p/sandbox/zdhq6m

The online sandbox gives a permission error but you should be able to open the sandbox in VS Code

I used the provided example but migrated `axios `to `fetch` and used a different url because the url in the example was using html instead of json.
![image](https://github.com/linmasahiro/vue3-table-lite/assets/25219229/30f94db5-e60d-450f-a328-5d9682db8459)

I will turn off static mode for now in my application.
