### ISSUE TITLE
Hero text is visible on the side nav

### ISSUE THREAD

**Issue by Joshua-Nweze** [linmasahiro/vue3-table-lite#98]
This is seen [here](https://vue3-lite-table.vercel.app/simple-examples)

![Screenshot 2023-10-13 160135](https://github.com/linmasahiro/vue3-table-lite/assets/101072509/d314d675-a28f-454d-9a6f-bcab50bfc91a)

**Comment by linmasahiro** [comment]
Hi, @Joshua-Nweze 
Thanks for your issue, but I don't know how to find  the link from document docs.
Can you tell me your step? Thx.

**Comment by linmasahiro** [comment]
OK, I found my README.md was wrong link, and I fixed it, but I am not resolve docs bug

**Comment by Joshua-Nweze** [comment]
Have you found the issue?

**Comment by linmasahiro** [comment]
> Have you found the issue?

It's wrong URL on README, access [here](https://vue3-lite-table.vercel.app/simple-examples.html) please.
